---
- name: Install PuppetLabs releasea RPM
  yum:
    #fix this
    #name: "{{ item }}.noarch.rpm"
    name: http://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
    state: "present"
    # fix this
    #with_items:
    #  - "http://yum.puppetlabs.com/puppetlabs-release-pc1-el-{{ ansible_distribution_version.split('.')[0] }}"

- name: update_packages
  yum:
    name: puppetlabs-release-pc1
    state: "present"
    update_cache: "yes"

- name: install_puppet
  yum:
    name: "puppet-agent"
    state: "present"

- name: add_master_ip_entry
  lineinfile: 
    dest: /etc/hosts 
    regexp: '.*puppet$' 
    line: "{{pa_master_addr}}  puppet" 
    state: "present"
  when: pa_master_addr is defined

- name: write puppet conf
  template:
    src:   puppet.conf.j2 
    dest:  /etc/puppetlabs/puppet/puppet.conf
    owner: root
    group: root
    mode:  u=rwx,g=rx,o=rx
  when: pa_master_fqdn is defined

- name: start_puppet
  service: 
    name: 'puppet.service' 
    enabled: 'yes'
    state: 'started'
